### ISSUE TITLE
A error in Minetest 0.4.17.1

### ISSUE THREAD

**Issue by Hagb** [MuhdNurHidayat/unicodeparser#1]
I got a error

> 2018-07-26 00:51:37: ERROR[Main]: ModError: Failed to load and run script from /home/hagb/.minetest/mods/unicodeparser/init.lua:
> 2018-07-26 00:51:37: ERROR[Main]: /home/hagb/.minetest/mods/unicodeparser/init.lua:44: attempt to call field 'register_on_formspec_input' (a nil value)
> 2018-07-26 00:51:37: ERROR[Main]: stack traceback:
> 2018-07-26 00:51:37: ERROR[Main]: 	/home/hagb/.minetest/mods/unicodeparser/init.lua:44: in main chunk
> 2018-07-26 00:51:37: ERROR[Main]: Check debug.txt for details.

Thanks!

**Comment by mnh48** [comment]
it is a client-side mod... put it into `.minetest/clientmods` instead of `.minetest/mods`
if the directory `clientmods` does not exist, create it...
more info here: https://wiki.minetest.net/Installing_Client-Side_Mods

**Comment by mnh48** [comment]
Let me know if it still gives error after installing into the correct directory.
You will also need to enable client modding from advanced settings, and change the value in `mods.conf` in the `clientmods` directory from `load_mod_unicodeparser = false` to `load_mod_unicodeparser = true`

**Comment by Hagb** [comment]
Another error:
> 2018-07-26 20:32:24: ERROR[Main]: ModError: Runtime error from mod 'unicodeparser' in callback on_sending_message(): /home/hagb/.minetest/clientmods/unicodeparser/init.lua:95: attempt to compare nil with number
> 2018-07-26 20:32:24: ERROR[Main]: Check debug.txt for details.

It seems that all chars must be as unicode form, so I writed a shell script to automatically do that. 
Thanks!

**Comment by Hagb** [comment]
Oh! I find what the problem is. I will try to solve it.

**Comment by mnh48** [comment]
Closed as #2 is merged.
